Repository jboss-container-images/jboss-eap-modules, pull requests merged in 2018-11, with the labels that each got.

#37 [CLOUD-3003] - Move EAP tests from cct_module to jboss-eap-modules repo
  tests/features/6/basic.feature
  tests/features/6/datasource.feature
  tests/features/6/gc.feature
  tests/features/6/hawkular.feature
  tests/features/6/jgroups.feature
  tests/features/6/logging.feature
  tests/features/6/messaging.feature
  tests/features/6/resource_adapters.feature
  tests/features/6/s2i.feature
  tests/features/6/security_domains.feature
  tests/features/6/sso.feature
  tests/features/6/variable_expansion.feature
  tests/features/7/7.1/basic.feature
  tests/features/7/7.1/jgroups.feature
  tests/features/7/7.1/logging.feature
  tests/features/7/7.1/security_domains.feature
  tests/features/7/7.2/basic.feature
  tests/features/7/7.2/jgroups.feature
  tests/features/7/7.2/logging.feature
  tests/features/7/7.2/security_domains.feature
  tests/features/7/CD/basic.feature
  tests/features/7/CD/jgroups.feature
  tests/features/7/CD/logging.feature
  tests/features/7/CD/security_domains.feature
  tests/features/7/basic.feature
  tests/features/7/datasource.feature
  tests/features/7/filters.feature
  tests/features/7/gc.feature
  tests/features/7/hawkular.feature
  tests/features/7/https.feature
  tests/features/7/jgroups.feature
  tests/features/7/messaging.feature
  tests/features/7/resource_adapters.feature
  tests/features/7/s2i.feature
  tests/features/7/security_domains.feature
  tests/features/7/shutdown.feature
  tests/features/7/sso.feature
  tests/features/7/variable_expansion.feature
  tests/features/LICENSE
  tests/features/README.md
  tests/features/common.feature
  tests/features/openshift.feature
Labels: Approved, Dev, QE

#39 Correct EAP 7.2 behave tests label
  tests/features/7/7.2/basic.feature
Labels: Approved, Dev

#40 [CLOUD-3016] - updates for jgroups config & updated upstream DNS_PING
  jboss-eap-cd14-openshift/added/standalone-openshift.xml
  jboss-eap-config-jgroups/added/launch/ha.sh
  jboss-eap-config-jgroups/module.yaml
  jboss-eap-config-jgroups/test/ha.bats
  jboss-eap72-openshift/added/standalone-openshift.xml
Labels: Approved, Dev, QE

#43 [CLOUD-3025] Allow selected EAP CD 14 / EAP 7.2.0.CR1 tests with updated JGroups
  tests/features/7/basic.feature
Labels: Needs Review
