Repository jboss-container-images/jboss-eap-modules, pull requests merged in 2019-07, with the labels that each got.

#121 CLOUD-3319 - remove mysql & postgres from CD 17 standalone-openshift.xml
  jboss-eap-config-openshift/CD17.0/added/standalone-openshift.xml
Labels: needs review

#115 [7.2.x-openjdk11] - CLOUD-2742 - Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings
  os-eap-probes/1.0/added/livenessProbe.sh
  os-eap-probes/1.0/added/readinessProbe.sh
  os-eap-probes/2.0/added/livenessProbe.sh
  os-eap-probes/2.0/added/readinessProbe.sh
Labels: 7.2.x-openjdk11, approved, dev-approved

#123 [CLOUD-3320] - Missing LOGGER-CATEGORY in config breaks tests
  jboss-eap72-openshift/added/standalone-openshift.xml
  os-eap7-launch/added/launch/configure_logger_category.sh
  os-eap7-launch/tests/bats/logging/configure-logging-category.bats
Labels: 7.2.x, approved, dev-approved

#114 CLOUD-3245 - [7.2.x] Allow kubernetes to control probe retries; avoid probes taking longer than kubernetes timeout settings
  os-eap-probes/added/livenessProbe.sh
  os-eap-probes/added/probes/probe/dmr.py
  os-eap-probes/added/readinessProbe.sh
Labels: 7.2.x, needs review

#125 [CLOUD-3325] - openshift-migrate.sh terminates with Max retries exceeded with url: /management
  os-eap-migration/added/launch/openshift-migrate-common.sh
Labels: approved, dev-approved

#126 [CLOUD-3328] verify insertion of txn recovery marker succeed otherwise do not proceed
  os-eap-txnrecovery/bash/added/partitionPV.sh
Labels: 7.2.x-openjdk11, approved, dev-approved

#98 [CLOUD-3206] Add default hostname ports to SSO client configuration
  os-eap-sso/added/keycloak.sh
  os-eap-sso/tests/bats/hostname-discovery.bats
Labels: approved, dev-approved
