Repository jboss-container-images/jboss-eap-modules, pull requests merged in 2019-05, with the labels that each got.

#81 [CLOUD-3192] Update openshift-ping version
  os-eap64-ping/configure.sh
  os-eap64-ping/module.yaml
  os-eap7-ping/configure.sh
  os-eap7-ping/module.yaml
Labels: 6.4.x, approved, dev-approved

#82 CLOUD-3128 - EAP 7.2 UBI OpenShift image
  os-eap-db-drivers/module.yaml
  os-eap-probes/1.0/added/livenessProbe.sh
  os-eap-probes/1.0/added/probe_common.sh
  os-eap-probes/1.0/added/probes/probe/__init__.py
  os-eap-probes/1.0/added/probes/probe/api.py
  os-eap-probes/1.0/added/probes/probe/dmr.py
  os-eap-probes/1.0/added/probes/probe/eap/__init__.py
  os-eap-probes/1.0/added/probes/probe/eap/dmr.py
  os-eap-probes/1.0/added/probes/probe/eap/jolokia.py
  os-eap-probes/1.0/added/probes/probe/jolokia.py
  os-eap-probes/1.0/added/probes/runner.py
  os-eap-probes/1.0/added/readinessProbe.sh
  os-eap-probes/1.0/configure.sh
  os-eap-probes/1.0/module.yaml
  os-eap-probes/2.0/added/livenessProbe.sh
  os-eap-probes/2.0/added/probe_common.sh
  os-eap-probes/2.0/added/probes/probe/__init__.py
  os-eap-probes/2.0/added/probes/probe/api.py
  os-eap-probes/2.0/added/probes/probe/dmr.py
  os-eap-probes/2.0/added/probes/probe/eap/__init__.py
  os-eap-probes/2.0/added/probes/probe/eap/dmr.py
  os-eap-probes/2.0/added/probes/probe/eap/jolokia.py
  os-eap-probes/2.0/added/probes/probe/jolokia.py
  os-eap-probes/2.0/added/probes/runner.py
  os-eap-probes/2.0/added/readinessProbe.sh
  os-eap-probes/2.0/configure.sh
  os-eap-probes/2.0/module.yaml
  os-eap-python/3.6/configure.sh
  os-eap-python/3.6/module.yaml
  os-eap-ubi/8/configure.sh
  os-eap-ubi/8/module.yaml
  tests/features/7/7.2/basic.feature
  tests/features/7/basic.feature
  tests/features/7/datasource.feature
  tests/features/7/hawkular.feature
Labels: needs review

#86 [CLOUD-3199] - added warn message in case of SSO_SECRET is empty
  os-eap-sso/added/keycloak.sh
Labels: approved, dev-approved

#87 [CLOUD-3200] - querying k8s api to discover generated routes
  os-eap-sso/added/keycloak.sh
  os-eap-sso/tests/bats/README.md
  os-eap-sso/tests/bats/common.bash
  os-eap-sso/tests/bats/hostname-discovery.bats
  os-eap-sso/tests/bats/mock_responses/multi-route.json
  os-eap-sso/tests/bats/mock_responses/no-route.json
  os-eap-sso/tests/bats/mock_responses/single-route.json
  os-eap-sso/tests/bats/server/README.md
  os-eap-sso/tests/bats/server/shinatra.sh
Labels: approved, dev-approved

#88 [CLOUD-3191] Update openshift-ping version
  os-eap64-ping/configure.sh
  os-eap64-ping/module.yaml
  os-eap7-ping/configure.sh
  os-eap7-ping/module.yaml
Labels: 7.2.x, approved, dev-approved

#93 [CLOUD-3210] 7.2.x-openjdk11] Update ping modules to 1.2.5
  os-eap64-ping/configure.sh
  os-eap64-ping/module.yaml
  os-eap7-ping/configure.sh
  os-eap7-ping/module.yaml
Labels: 7.2.x-openjdk11, needs acks, needs review

#100 [CLOUD-3211] update mongodb driver to mongodb36
  os-eap-db-drivers/configure.sh
  os-eap-db-drivers/module.yaml
Labels: approved, dev-approved

#101 [CLOUD-3223] update mongodb driver to mongodb36
  os-eap-db-drivers/configure.sh
  os-eap-db-drivers/module.yaml
Labels: 6.4.x, approved, dev-approved, needs acks

#96 CLOUD-3198 Datasource generation should escape ampersand
  os-eap-datasource/1.0/added/launch/datasource-common.sh
  os-eap-launch/added/launch/datasource-common.sh
Labels: approved, dev-approved

#85 CLOUD-3180 - update EAP SSO Adapters to RH-SSO 7.3
  os-eap64-sso/configure.sh
  os-eap64-sso/module.yaml
  os-eap70-sso/configure.sh
  os-eap70-sso/module.yaml
Labels: needs review

#103 [CLOUD-3235] - Update ping modules to fix certificate issue in OCP 4.1
  os-eap64-ping/module.yaml
  os-eap7-ping/module.yaml
Labels: approved, dev-approved

#105 [CLOUD-3235] - Fixing missed VERSION variable value
  os-eap64-ping/configure.sh
  os-eap7-ping/configure.sh
Labels: approved, dev-approved

#102 CLOUD-3233 - fix logging tests
  os-eap7-launch/tests/bats/logging/configure-logging-category.bats
Labels: needs review

#92 [7.2.x-openjdk11] [CLOUD-3209] SSO_SECRET parameter should be required if configuring RH-SSO integration
  os-eap-sso/added/keycloak.sh
Labels: 7.2.x-openjdk11, needs acks, needs review

#91 [CLOUD-3208] - [7.2.x] SSO_SECRET parameter should be required if configuring RH-SSO integration
  os-eap-sso/added/keycloak.sh
Labels: 7.2.x, approved, dev-approved, needs acks

#89 CLOUD-3204 [7.2.x] Discover application routes during Keycloak client configuration via Kubernetes API
  os-eap-sso/added/keycloak.sh
  os-eap-sso/tests/bats/README.md
  os-eap-sso/tests/bats/common.bash
  os-eap-sso/tests/bats/hostname-discovery.bats
  os-eap-sso/tests/bats/mock_responses/multi-route.json
  os-eap-sso/tests/bats/mock_responses/no-route.json
  os-eap-sso/tests/bats/mock_responses/single-route.json
  os-eap-sso/tests/bats/server/README.md
  os-eap-sso/tests/bats/server/shinatra.sh
Labels: 7.2.x, approved, dev-approved

#94 [7.2.x] [CLOUD-3212] Update bats tests to run with new CI
  os-eap-launch/test/datasource.bats
  os-eap7-launch/added/launch/tx-datasource.sh
  os-eap7-launch/tests/bats/datasource/common.bash
  os-eap7-launch/tests/bats/datasource/configure.bats
  os-eap7-launch/tests/bats/datasource/expectations/datasources_ibmdb2_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_mysql_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_other_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_other_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_postgresql_nourl_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_pool_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/datasources_sybase_validation_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/prefix_ibmdb2_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/prefix_mysql_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/prefix_oracle_xa.xml
  os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_nonxa.xml
  os-eap7-launch/tests/bats/datasource/expectations/prefix_postgresql_xa.xml
  os-eap7-launch/tests/bats/launch-common/launch-common.bats
  os-eap7-launch/tests/bats/logging/configure-logging-category.bats
  run-all-tests.sh
  test-common/log_utils.bash
  test-common/openshift-node-name.sh
  test-common/xml_utils.bash
Labels: 7.2.x, approved, dev-approved

#95 [CLOUD-3213] - [7.2.x-openjdk11] Update bats tests to run with new CI
  jboss-eap-cd-openshift-launch/added/launch/openshift-common.sh
  jboss-eap-cd14-openshift/added/standalone-openshift.xml
  jboss-eap-cd15-openshift/added/standalone-openshift.xml
  jboss-eap72-openshift/added/standalone-openshift.xml
  os-eap7-launch/added/launch/configure_logger_category.sh
  os-eap7-launch/added/launch/openshift-common.sh
  os-eap7-launch/tests/bats/logging/configure-logging-category.bats
  os-eap70-openshift/added/standalone-openshift.xml
  os-eap71-openshift/added/standalone-openshift.xml
Labels: 7.2.x-openjdk11, approved, dev-approved, needs acks

#76 CLOUD-3179 - update CTF tests for CD16
  tests/features/7/CD/basic.feature
  tests/features/7/CD/jgroups.feature
  tests/features/7/CD/logging.feature
  tests/features/7/CD/security_domains.feature
  tests/features/7/basic.feature
  tests/features/7/datasource.feature
  tests/features/7/filters.feature
  tests/features/7/gc.feature
  tests/features/7/hawkular.feature
  tests/features/7/https.feature
  tests/features/7/jgroups.feature
  tests/features/7/messaging.feature
  tests/features/7/resource_adapters.feature
  tests/features/7/s2i.feature
  tests/features/7/security_domains.feature
  tests/features/7/shutdown.feature
  tests/features/7/sso.feature
  tests/features/7/variable_expansion.feature
  tests/features/common.feature
  tests/features/openshift.feature
Labels: approved, dev-approved, needs review

#109 [CLOUD-3237] Update ping modules to fix certificate issue in OCP 4.1
  os-eap64-ping/configure.sh
  os-eap64-ping/module.yaml
  os-eap7-ping/configure.sh
  os-eap7-ping/module.yaml
Labels: 7.2.x-openjdk11, approved, dev-approved

#107 [CLOUD-3236] - Update ping modules to fix certificate issue in OCP 4.1
  os-eap64-ping/configure.sh
  os-eap64-ping/module.yaml
  os-eap7-ping/configure.sh
  os-eap7-ping/module.yaml
Labels: 7.2.x, approved, dev-approved

#106 [CLOUD-3230] Datasource generation should escape ampersand
  os-eap-launch/added/launch/datasource-common.sh
Labels: 7.2.x, approved, dev-approved

#104 [CLOUD-3218] update mongodb driver to mongodb36
  os-eap-db-drivers/configure.sh
  os-eap-db-drivers/module.yaml
Labels: 7.2.x, approved, dev-approved

#108 [CLOUD-3216] update EAP SSO Adapters to RH-SSO 7.3.1
  os-eap64-sso/configure.sh
  os-eap64-sso/module.yaml
  os-eap70-sso/configure.sh
  os-eap70-sso/module.yaml
Labels: 7.2.x, approved, dev-approved

#110 [CLOUD-3220] update EAP SSO Adapters to RH-SSO 7.3.1
  os-eap64-sso/configure.sh
  os-eap64-sso/module.yaml
  os-eap70-sso/configure.sh
  os-eap70-sso/module.yaml
Labels: 7.2.x-openjdk11, approved, dev-approved

#90 CLOUD-3207 [7.2.x-openjdk11] Discover application routes during Keycloak client configuration via Kubernetes API
  os-eap-sso/added/keycloak.sh
  os-eap-sso/tests/bats/README.md
  os-eap-sso/tests/bats/common.bash
  os-eap-sso/tests/bats/hostname-discovery.bats
  os-eap-sso/tests/bats/mock_responses/multi-route.json
  os-eap-sso/tests/bats/mock_responses/no-route.json
  os-eap-sso/tests/bats/mock_responses/single-route.json
  os-eap-sso/tests/bats/server/README.md
  os-eap-sso/tests/bats/server/shinatra.sh
Labels: 7.2.x-openjdk11, needs acks, needs review

#111 [7.2.x-openjdk11] [CLOUD-3209] SSO_SECRET parameter should be required if configuring RH-SSO integration
  os-eap-datasource/1.0/added/launch/datasource-common.sh
  os-eap-launch/added/launch/datasource-common.sh
Labels: 7.2.x-openjdk11, needs review
